// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQP8tnbhBM0_QX_NrC85wXJXTO_L8obX4',
    appId: '1:181388128583:web:4645397a98301c4552dc62',
    messagingSenderId: '181388128583',
    projectId: 'sorta-3df17',
    authDomain: 'sorta-3df17.firebaseapp.com',
    storageBucket: 'sorta-3df17.firebasestorage.app',
    measurementId: 'G-X0NXHN6QHS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcM2o9mDAHVmFBkKFxb4NZdeBZ_aSs1EM',
    appId: '1:181388128583:ios:ae579d2e7979455352dc62',
    messagingSenderId: '181388128583',
    projectId: 'sorta-3df17',
    storageBucket: 'sorta-3df17.firebasestorage.app',
    iosBundleId: 'com.affinityafrica.actually',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAAsfFHn8k8Jj2ixDeXJh9Vo_hSSImabY',
    appId: '1:181388128583:android:8de91343e34f86c652dc62',
    messagingSenderId: '181388128583',
    projectId: 'sorta-3df17',
    storageBucket: 'sorta-3df17.firebasestorage.app',
  );
}
